#!/usr/bin/env escript
%% -*- erlang -*-

%% a simple, cross platform web server. Public domain.

main(_) ->
    ServiceConfig = [{port, 8081},
                     {server_name, "simple static http server"},
                     {server_root, "."},
                     {document_root, "index.html"},
                     {modules, [mod_range, mod_head, mod_get, mod_log, mod_dir]}
                    ],
    ok = inets:start(),
    {ok, _} = inets:start(httpd, ServiceConfig),
    run_loop().

run_loop() ->
    receive
        _ ->
            run_loop()
    end.
